### PR TITLE
docs: Fix a few typos

### PR DESCRIPTION
**Pull request by timgates42**
There are small typos in:
- library/cpp/getopt/small/modchooser.h
- library/cpp/threading/future/subscription/README.md

Fixes:
- Should read `subscriptions` rather than `suscriptions`.
- Should read `automatically` rather than `automaticly`.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Comment by kizill** [comment]
Hello! Sorry, but we don't accept changes in contrib/ folder, as files in it is a copy from relevant opensource projects, so please make a PR to them :)
We can accept changes in library/cpp, so please update you PR :)

**Comment by timgates42** [comment]
Thanks @kizill have updated

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@timgates42, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by timgates42** [comment]
thx @kizill updated the PR description as requested in the guidelines

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [2535037](https://a.yandex-team.ru/review/2535037)

**Comment by andrey-khropov** [comment]
This PR has been merged as a part of https://github.com/catboost/catboost/commit/d12b1712a9f447f19375c32b52409243961d6722

**Pull request closed without merging**
