### PR TITLE
kwargs for convert_to_onnx_object

### PR DESCRIPTION
**Pull request by monkey0head**
added kwargs to process arguments from onnxmltools interface

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1262102](https://a.yandex-team.ru/review/1262102)

**Comment by arcadia-devtools** [comment]
Check [1262102](https://a.yandex-team.ru/review/1262102) passed

**Pull request merged**
