### PR TITLE
Support building catboost Python package for `linux/arm64`

### PR DESCRIPTION
**Pull request by arestifo**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

This PR makes some small build changes to get `catboost` Python package building on `linux/arm64`. I tested using Python `3.9.14` and am using it in my team, where it is holding up very well.

### CODE REVIEW

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
dear @arestifo 
thank you so much for this pr ❤️ 
we will check it on our side, and will get back to you in 1-2 weeks, hopefully

**Comment by arestifo** [comment]
Sounds good! I forgot to mention I only tested this in a cross-compilation `x86_64` environment, you can check my build notes here: https://github.com/catboost/catboost/issues/2091.

Not sure what kind of effort it will take to get it building natively on `linux/arm64`, but since it builds on `x86_64` you can at least integrate this fix with your CI pipeline so we can have pre-built wheels for `linux/arm64`

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arestifo** [comment]
Any updated here? Can I help with anything?

**Review by Evgueni-Petrov-aka-espetrov — CHANGES_REQUESTED** [review]

**Comment by andrey-khropov** [comment]
We've switched from Ya Make - based build to CMake - based and from mk_wheel.py to setup.py for building Python packages.
CatBoost can now be built for Linux aarch64 using this approach and Linux aarch64 artifacts are available since release 1.2.
 
These changes make this PR obsolete.

**Pull request closed without merging**
