### PR TITLE
 [node-package] Rename node-package from 'catboost-model' to 'catboost'

### PR DESCRIPTION
**Pull request by IKholopov**
#1592

1. Renaming all references to package name from `catboost-model` to `catboost`.
2. Adding `config.json` generated for v0.25.1 catboost release
3. Renaming package and updating version. Increasing major version to 2.*.* as the version of the package named `catboost` being served right now has been given a version of 1.1.1. New catboost 'official' version is not compatible with the interface of that version.

### CODE REVIEW

**Comment by IKholopov** [comment]
@nikitxskv

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1772914](https://a.yandex-team.ru/review/1772914)

**Pull request merged**
