### PR TITLE
Fixed deprecated imports

### PR DESCRIPTION
**Pull request by Trollgeir**
Reference to issue:  https://github.com/catboost/catboost/issues/1212

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Trollgeir, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by Trollgeir** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1184353](https://a.yandex-team.ru/review/1184353)

**Comment by arcadia-devtools** [comment]
Check [1184353](https://a.yandex-team.ru/review/1184353) passed

**Pull request merged**
