### PR TITLE
Add Google Colab tutorial for regression in catboost

### PR DESCRIPTION
**Pull request by col14m**
Add new tutorial for CatBoost to solve regression problems on Google Colaboratory on CPU and GPU. 
Your Google Kolab tutorial on the classification problem was used as a base.

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@col14m, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [816409](https://a.yandex-team.ru/review/816409)

**Comment by arcadia-devtools** [comment]
Check [816409](https://a.yandex-team.ru/review/816409) passed

**Comment by col14m** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by annaveronika** [comment]
@col14m Thank you very much for your contribution!

**Comment by col14m** [comment]
@annaveronika glad to help

**Pull request merged**
