### PR TITLE
Added test for test_compare

### PR DESCRIPTION
**Pull request by vitaliy505**
Added functional tests for `compare` function from core.py

I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=ru].

### CODE REVIEW

**Comment by vitaliy505** [comment]
@kizill please, review and merge

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 709151

**Comment by annaveronika** [comment]
Tests should work even if wigets are not installed.
Currently tests are failing:
```
catboost/python-package/ut/medium/test.py:2792: in test_compare
    model.compare(model2, Pool(dataset, label=train_labels), ["RMSE"])
catboost/python-package/catboost/core.py:1526: in compare
    raise ImportError(str(e))
E   ImportError: No module named widget
```

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 715353

**Comment by annaveronika** [comment]
The test is still failing
catboost/python-package/ut/medium/test.py:2801: in test_compare
    else pytest.fail(str(ie))
E   Failed: No module named widget

**Comment by vitaliy505** [comment]
@annaveronika it should be marked as "expected failure". I will recheck behaviour

**Comment by andrey-khropov** [comment]
> @annaveronika it should be marked as "expected failure". I will recheck behaviour

Hello! Any progress on this issue?

**Comment by andrey-khropov** [comment]
> > @annaveronika it should be marked as "expected failure". I will recheck behaviour
> 
> Hello! Any progress on this issue?

Hello again! Any progress or we should close the PR?

**Comment by vitaliy505** [comment]
@andrey-khropov, hello! I apologize for such a late reply, it was not possible to answer earlier.
I tried to reproduce the issue and ran into a problem:
```
(.env3-catboost) C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost\catboost\python-package>..\..\ya make -tA -L
------- [SB] {default-win-x86_64, debug, FAILED} $(B)/catboost/python-package/ut/large/pkg/python3.6.tar.gz
command C:\Users\vurusovs\.ya\tools\v3\173608136/python C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost/build/scripts/fetch_from_sandbox.py --resource-id 412720651 --copy-to-dir . python3.6.tar.gz failed with exit code 12
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
ERROR:root:<urlopen error ('_ssl.c:574: The handshake operation timed out',)>
Traceback (most recent call last):
  File "C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost/build/scripts/fetch_from_sandbox.py", line 180, in <module>
    main(opts, args)
  File "C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost/build/scripts/fetch_from_sandbox.py", line 167, in main
    fetched_file, file_name = fetch(opts.resource_id, custom_fetcher)
  File "C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost/build/scripts/fetch_from_sandbox.py", line 116, in fetch
    raise ResourceInfoError(str(e))
ResourceInfoError: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>
Failed
```
My proposal about this issue - proxy of the network. Perhaps you know how to solve this problem?

**Comment by andrey-khropov** [comment]
> @andrey-khropov, hello! I apologize for such a late reply, it was not possible to answer earlier.
> I tried to reproduce the issue and ran into a problem:
> 
> ```
> (.env3-catboost) C:\Users\vurusovs\Desktop\my_work\Drakon5999\catboost\catboost\python-package>..\..\ya make -tA -L
...
> My proposal about this issue - proxy of the network. Perhaps you know how to solve this problem?

Hi! Turns out the issue here is that python-package/ut/large needs Yandex's internal infrastructure services access that is not supported in open source right now. 

So, you can build the package using running 'ya make' in 'catboost/python-package/catboost' and run tests using 'ya make' in 'catboost/python-package/catboost/ut/medium'.

**Comment by vitaliy505** [comment]
@andrey-khropov @annaveronika Hello! I rechecked the test and resolved issue with failure. Could you check the last version?

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [783584](https://a.yandex-team.ru/review/783584)

**Comment by arcadia-devtools** [comment]
Check [783584](https://a.yandex-team.ru/review/783584) passed

**Pull request merged**
