### PR TITLE
imports VERSION from version.py into setup.py

### PR DESCRIPTION
**Pull request by david-waterworth**
My previous pull request contained the package version hard coded, this corrects this by importing the version.py from from the package.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [799194](https://a.yandex-team.ru/review/799194)

**Comment by arcadia-devtools** [comment]
Check [799194](https://a.yandex-team.ru/review/799194) passed

**Comment by kizill** [comment]
Thank you very much!

**Pull request merged**
