### PR TITLE
Add CatBoostClassifier predict_log_proba catboost_clickhouse_sprint_02.02.2019 v2

### PR DESCRIPTION
**Pull request by tswr**
A new PR to add predict_log_proba and such instead of https://github.com/catboost/catboost/pull/651

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@tswr, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by tswr** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1037937](https://a.yandex-team.ru/review/1037937)

**Comment by arcadia-devtools** [comment]
Check [1037937](https://a.yandex-team.ru/review/1037937) failed: 1 test(s) broken

**Comment by LyzhinIvan** [comment]
@arcadia-devtools Ship it!

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request updated: [1037937](https://a.yandex-team.ru/review/1037937)

**Comment by arcadia-devtools** [comment]
Check [1037937](https://a.yandex-team.ru/review/1037937) passed

**Pull request merged**
