### PR TITLE
Fix dynamic fold init v2

### PR DESCRIPTION
**Pull request by Andrew-Angrew**
Clone of https://github.com/catboost/catboost/pull/1159
(cloned in order to merge)

Fixed problems:
  Baseline were not set to approxes in bodies of bodytails.
  Memory overuse bt.PairwiseWeights

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1117403](https://a.yandex-team.ru/review/1117403)

**Comment by arcadia-devtools** [comment]
Check [1117403](https://a.yandex-team.ru/review/1117403) failed: 7 test(s) broken

**Pull request merged**
