### PR TITLE
core.py: update get_feature_importance compatibility for python3

### PR DESCRIPTION
**Pull request by harshalchaudhari35**
* Add builtins modules to support imports in python3

### CODE REVIEW

**Comment by annaveronika** [comment]
@harshalchaudhari35 Could you please resolve the conflicts?

**Comment by harshalchaudhari35** [comment]
@annaveronika Should be resolved now. Please check

**Comment by harshalchaudhari35** [comment]
@annaveronika Please review as the conflict is resolved. Thanks

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@harshalchaudhari35, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1045747](https://a.yandex-team.ru/review/1045747)

**Comment by arcadia-devtools** [comment]
Check [1045747](https://a.yandex-team.ru/review/1045747) passed

**Comment by harshalchaudhari35** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by harshalchaudhari35** [comment]
```I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en```

**Pull request merged**
