### PR TITLE
Fixed wrong sign in Lq gradients

### PR DESCRIPTION
**Pull request by ilya-pchelintsev**
I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=en](https://yandex.ru/legal/cla/?lang=en).

### CODE REVIEW

**Comment by LyzhinIvan** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@LyzhinIvan, internal review request created: [1161947](https://a.yandex-team.ru/review/1161947)

**Comment by arcadia-devtools** [comment]
Check [1161947](https://a.yandex-team.ru/review/1161947) passed

**Pull request merged**
