### PR TITLE
AUC tutorial

### PR DESCRIPTION
**Pull request by monkey0head**
Tutorial on CatBoost AUC

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@monkey0head, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by monkey0head** [comment]
@arcadia-devtools I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=ru

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1215827](https://a.yandex-team.ru/review/1215827)

**Comment by arcadia-devtools** [comment]
Check [1215827](https://a.yandex-team.ru/review/1215827) passed

**Pull request merged**
