### PR TITLE
partial fix sprint tikit 10

### PR DESCRIPTION
**Pull request by ai-maxim**
Before submitting a pull request, please do the following steps:

1. Read instructions for contributors [here](https://tech.yandex.com/catboost/doc/dg/concepts/development-and-contributions-docpage/).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the CLA. 

I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=ru].

### CODE REVIEW

**Comment by ai-maxim** [comment]
убрал все атрибуты с подчерком так, что sklearn перестал на них жаловаться, но теперь он жалуется вот так:

Traceback (most recent call last):
File "_catboost.pyx", line 1384, in _catboost.get_float_feature
File "_catboost.pyx", line 882, in _catboost._FloatOrNan
TypeError: Cannot convert obj {'foo': 'bar'} to float

**Comment by ai-maxim** [comment]
это мой тест:
import sklearn.utils.estimator_checks as ec
from catboost import CatBoostRegressor
ec.check_estimator(CatBoostRegressor)

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 711103

**Comment by annaveronika** [comment]
Tests are failing:

catboost/pytest/test.py:5172: in test_snapshot_without_random_seed
    random_seed = cb_model.random_seed_
E   AttributeError: 'CatBoost' object has no attribute 'random_seed_'

catboost/python-package/ut/medium/test.py:3495: in test_deprecated_behavoir
    model.metadata_
E   AttributeError: 'CatBoost' object has no attribute 'metadata_'

catboost/python-package/ut/medium/test.py:2484: in test_feature_names_from_model
    print(model.feature_names_)
E   AttributeError: 'CatBoost' object has no attribute 'feature_names_'

Please run the tests, check that they are passing, and update the code.

**Comment by annaveronika** [comment]
@ai-maxim Do you plan to fix the errors?

**Comment by annaveronika** [comment]
Discussed in person. There is no plan for fixes, so we need to discard :(

**Pull request closed without merging**
