### PR TITLE
Expose more model metadata in the Java API

### PR DESCRIPTION
**Pull request by mikekap**
There's a few things in this PR - let me know if you'd prefer I split it out.
 - Fixes an issue with unicode handling in the JNI layer. This isn't really an issue now, but is with the changes that expose the model info dictionary.
 - Exposes the model info dictionary ("metadata") in the java interface
 - Exposes feature information - including type, flat/non-flat indices, and some details depending on type.

One unrelated thing I noticed - running `mvn test` in a docker container currently fetches the `linux-ppc64le` version of `ya` instead of the x86_64. Not sure if it's my fault somehow, but I had to append `_musl` to my platform name to get the right binary.

### CODE REVIEW

**Comment by kizill** [comment]
Thank you a lot for a great contribution!
I've forwarded information about erroneous `linux-ppc64le` platform to our devtools team, hope they'll fix it soon.

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1322353](https://a.yandex-team.ru/review/1322353)

**Comment by arcadia-devtools** [comment]
Check [1322353](https://a.yandex-team.ru/review/1322353) failed: 1 build(s) broken

**Comment by kizill** [comment]
Got a compilation problem on windows:
```
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:377: error C2664: 'void JNIEnv_::SetIntArrayRegion(jintArray,jsize,jsize,const jint *)': cannot convert argument 4 from 'const int *' to 'const jint *'
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:377: note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:378: error C2664: 'void JNIEnv_::SetIntArrayRegion(jintArray,jsize,jsize,const jint *)': cannot convert argument 4 from 'const int *' to 'const jint *'
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:378: note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:380: error C2664: 'void JNIEnv_::SetIntArrayRegion(jintArray,jsize,jsize,const jint *)': cannot convert argument 4 from 'int *' to 'const jint *'
catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_catboostjniimpl.cpp:380: note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
....
```
Could you please fix them?

**Comment by mikekap** [comment]
@kizill I attempted to fix the errors with what the other code in this file does - not sure if I succeeded or not. I don't have a windows machine setup with which I could test unfortunately. Is there a chance @arcadia-devtools will tell me if the build is broken?

**Comment by kizill** [comment]
Yes, i'll run tests again and paste here compiler errors if any of them will persist.

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request updated: [1322353](https://a.yandex-team.ru/review/1322353)

**Comment by arcadia-devtools** [comment]
Check [1322353](https://a.yandex-team.ru/review/1322353) passed

**Comment by kizill** [comment]
Thank you a lot for your contribution 🥇

**Pull request merged**
