### PR TITLE
Support feature names in cat_features

### LINKED ISSUE #608: Support passing feature names in cat_features
Problem: I have a dataset which has data11.head(5) something like this:

```
Transaction_Type  Complaint_reason  Company_response  Consumer_disputes  \
0                 1                57                 3                  1   
1                 3                54                 9                  0   
2                17               130                 3                  0   
3                 4                60                 0                  0   
4                 2               145                 3                  0   

   Date_Difference  send_month  send_quarter  send_year  rec_month  \
0                0          11             4       2015         11   
1                0           7             3       2015          7   
2                0           7             3       2015          7   
3                0          12             4       2016         12   
4                0           9             3       2016          9   

   rec_quarter  rec_year  
0            4      2015  
1            3      2015  
2            3      2015  
3            4      2016  
4            3      2016 

```
It is a multiclassification problem.

When I run the code:
```
cat_features=list(data11.columns)

model1 = CatBoostClassifier(loss_function = 'MultiClass', random_seed=123)
model1.fit(x_train, y_train, cat_features)
model1.get_feature_importance()
y_pred1=model1.predict(x_test)
```

I get the error saying:

```

  File "C:\Anaconda3\lib\site-packages\catboost\core.py", line 326, in _check_cf_value
    raise CatboostError("Invalid cat_features[{}] = {} value type={}: must be int().".format(indx, feature, type(feature)))

CatboostError: Invalid cat_features[0] = Transaction_Type value type=<class 'str'>: must be int().
```

This means that the function detects the attribute 'Transaction_Type' as string, whereas all the columns have dtypes as int.

```
data11.dtypes

Transaction_Type     int64
Complaint_reason     int64
Company_response     int64
Consumer_disputes    int64
Date_Difference      int64
send_month           int64
send_quarter         int64
send_year            int64
rec_month            int64
rec_quarter          int64
rec_year             int64
dtype: object
```

Is this a bug? How is it possible that the int values in Transaction_Type are being detected as string?

Considering this as a classification problem, i convert all features to string:

```
for i in cat_features:
    data11[i]=data11[i].astype(str)
```

But still I get the same error when I run the model.

catboost version: {0.12.0}
Operating System: {Windows 7}
CPU: {i3}

### PR DESCRIPTION
**Pull request by infected-mushroom**
Fixes #608

### CODE REVIEW

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: 736553

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: 737215

**Pull request merged**
