### PR TITLE
Bring name of base CatBoost exception type to naming convention

### PR DESCRIPTION
**Pull request by infected-mushroom**
Issue #648

I hereby agree to the terms of the CLA available at [https://yandex.ru/legal/cla/?lang=ru].

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 721028

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 722165

**Comment by annaveronika** [comment]
@infected-mushroom Thanks a lot for the contribution!

**Pull request merged**
