### PR TITLE
Update lfqueue.h

### PR DESCRIPTION
**Pull request by dmsivkov**
Removed false sharing

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1286501](https://a.yandex-team.ru/review/1286501)

**Comment by arcadia-devtools** [comment]
Check [1286501](https://a.yandex-team.ru/review/1286501) failed: 2190 build(s) broken, 1431 test(s) broken

**Comment by andrey-khropov** [comment]
There's an issue with clang version that ``ya make`` uses for default build on Mac OS X now (7), it does not support alignas with big widths so please put this alignment under ``#ifndef __darwin__`` for now and leave the code in the present state for Mac OS X (under ``#else``).

Newer version of clang for ``ya make`` that would eliminate this issue is expected in 2020Q3.

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request updated: [1286501](https://a.yandex-team.ru/review/1286501)

**Comment by arcadia-devtools** [comment]
Check [1286501](https://a.yandex-team.ru/review/1286501) failed: 2207 build(s) broken, 1485 test(s) broken

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request updated: [1286501](https://a.yandex-team.ru/review/1286501)

**Comment by arcadia-devtools** [comment]
Check [1286501](https://a.yandex-team.ru/review/1286501) failed: 1283 test(s) broken

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1286501](https://a.yandex-team.ru/review/1286501)

**Comment by arcadia-devtools** [comment]
Check [1286501](https://a.yandex-team.ru/review/1286501) failed: 32 build(s) broken, 581 test(s) broken

**Pull request merged**
