### PR TITLE
Fix for Confusion matrix

### PR DESCRIPTION
**Pull request by dmsivkov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1096846](https://a.yandex-team.ru/review/1096846)

**Comment by arcadia-devtools** [comment]
Check [1096846](https://a.yandex-team.ru/review/1096846) passed

**Comment by annaveronika** [comment]
Thank you very much for this change!

**Pull request merged**
