### PR TITLE
Fix fold initialization for ordered boosting

### PR DESCRIPTION
**Pull request by Andrew-Angrew**
Fixed 2 problems:
1. Baseline were not set to approxes in bodies of bodytails.
2. Memory overuse bt.PairwiseWeights

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1105382](https://a.yandex-team.ru/review/1105382)

**Comment by arcadia-devtools** [comment]
Check [1105382](https://a.yandex-team.ru/review/1105382) failed: 24 test(s) broken

**Pull request closed without merging**
