### PR TITLE
Poisson tutorial

### PR DESCRIPTION
**Pull request by garkavem**
Tutorial for poisson regression with CatBoost.

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@garkavem, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by garkavem** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1206883](https://a.yandex-team.ru/review/1206883)

**Pull request merged**
