### PR TITLE
[node-package] GPU evaluation & e2e-test fix

### PR DESCRIPTION
**Pull request by IKholopov**
1. A method for enabling GPU evaluation of the model
2. Fix in E2E test. Bug was introduced in one of previous PRs (some files got reverted).

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1775116](https://a.yandex-team.ru/review/1775116)

**Comment by arcadia-devtools** [comment]
Check [1775116](https://a.yandex-team.ru/review/1775116) passed

**Pull request merged**
