### PR TITLE
Fix typo in the message about `dictionaryId` and `tokenizerId` #1331

### PR DESCRIPTION
**Pull request by feeeper**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

Typo was fixed: `dictionary_id` and `tokenizer_id` instead of `dictionaryId` and `tokenizerId`

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1313692](https://a.yandex-team.ru/review/1313692)

**Comment by arcadia-devtools** [comment]
Check [1313692](https://a.yandex-team.ru/review/1313692) failed: 3 test(s) broken

**Pull request merged**
