### PR TITLE
[node-package] Mac OS & Windows support for Node package

### PR DESCRIPTION
**Pull request by IKholopov**
#1592
- Adding the support for Mac OS as target platform for node-package
- Small fix in build scripts

### CODE REVIEW

**Comment by IKholopov** [comment]
- Added support for Windows as target platform
- Improved error handling in package preparation scripts

**Comment by IKholopov** [comment]
@nikitxskv

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1761596](https://a.yandex-team.ru/review/1761596)

**Pull request merged**
