### PR TITLE
Add TimeSeries Cross Validation

### PR DESCRIPTION
**Pull request by Kim2212**
Hello. Couple weeks ago we started using CatboostEvaluation for feature selection in our project, but with need different cross validation type (Time Series) cause our target is Time Series. Can you please review this pull request (and if it's correct merge) or just implement it by yourself. Thanks

### CODE REVIEW

**Comment by andrey-khropov** [comment]
Hello! 

Sorry for the delayed response.

Unfortunately your code is incorrect. Right now the implementation works this way - models are trained on each fold created in _Splitter._make_learn_folds and then evaluated on all other folds in each split (https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/eval/_fold_models_handler.py#L74-L90). For time series split you have to evaluate a trained model on data that is 'later' in time order. The simplest modification to make it possible is to change the condition to add fold for evaluation for a given model (https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/eval/_fold_models_handler.py#L81), something like that:

```python
            # add time_split_mode flag to function params
            ...
            for model_num, model in enumerate(case_models):
                if time_split_mode and (file_num <= (model_num + len(skipped_folds))):
                    continue
                elif file_num != model_num:
                    continue
                calcers[model_num].add(pool)
```

Note that it is different from train/test splits that sklearn.model_selection.TimeSeriesSplit generates (which I assume is what you originally intended).
Here in each evaluation train and test data sizes will be equal.
If this kind of fold splitting won't work for you we will have to discuss alternative, more elaborate solutions.

You also have to make sure that:

1) group_ids are consecutive when reading source data (see https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/eval/_readers.py). It might not be the case if data has non-trivial groups (trivial groups are just each sample is a group of size 1, it is the default), then there's a special field with index 'group_feature_num' in the source data that represents a certain group and there's no assumption that these ids are consecutive. You will have to reassign group_ids to consecutive numbers when reading source data to make sure _make_learn_folds creates folds in the same order.

2) 'has_time' parameter has to be passed in 'params' parameter of CatBoost constructor (https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_catboost-docpage/). Called here - https://github.com/catboost/catboost/blob/450c8f3721759ae164e1144773234b3a88ebd7c0/catboost/python-package/catboost/eval/_fold_models_handler.py#L107

**Comment by Kim2212** [comment]
When i use your modification and run CatBoostEvaluation in jupyter notebook, my kernel dies. Maybe it should be something like that:



`       last_fold = len(learn_folds) - 1
        metric_calcers = {}

                for model_num, model in enumerate(case_models):
                    if time_split_mode:
                        if file_num > (model_num + len(skipped_folds)):
                            calcers[model_num].add(pool)
                        if model_num == last_fold and model_num != file_num:
                                calcers[model_num].add(pool)
                    else:
                        if file_num != model_num:
                            calcers[model_num].add(pool)`

And is that possible to delete last fold( don't train on last fold and  evaluation on previous )?

**Comment by andrey-khropov** [comment]
> When i use your modification and run CatBoostEvaluation in jupyter notebook, my kernel dies. 

That is because I've had an error in my code.
it should have been

```py
                elif file_num == model_num:
                     continue
```
instead of

```py
                elif file_num != model_num:
                     continue
```

> Maybe it should be something like that:
> 
> ` last_fold = len(learn_folds) - 1
> metric_calcers = {}
> 
> ```
>             for model_num, model in enumerate(case_models):
>                 if time_split_mode:
>                     if file_num > (model_num + len(skipped_folds)):
>                         calcers[model_num].add(pool)
>                     if model_num == last_fold and model_num != file_num:
>                             calcers[model_num].add(pool)

^^
this last if is still incorrect - you can't add data parts for evaluation from 'previous' in time parts.

>                 else:
>                     if file_num != model_num:
>                         calcers[model_num].add(pool)`
> ```
> 
> And is that possible to delete last fold( don't train on last fold and evaluation on previous )?

Last fold should be deleted - yes, because there's no other data 'after' it to evaluate on. `calcers[model_num]` would be an empty list for it.

This correct version should be something like that (of course with proper passing of 'time_split_mode' as a parameter everywhere instead of being a global constant):

```py
Index: catboost/eval/_fold_models_handler.py
===================================================================
--- catboost/eval/_fold_models_handler.py	(revision 4231722)
+++ catboost/eval/_fold_models_handler.py	(working copy)
@@ -10,6 +10,9 @@
 from ._fold_model import FoldModel
 
 
+time_split_mode = True
+
+
 class FoldModelsHandler(object):
     """
     Class that is responsible for learning models and computing their metrics
@@ -71,7 +74,7 @@
                 elif self._metric_descriptions != metric_calcer.metric_descriptions():
                     raise CatboostError("Error: metric names should be consistent")
 
-        for file_num, fold_file in enumerate(learn_folds + skipped_folds + rest_folds):
+        for file_num, fold_file in enumerate(skipped_folds + learn_folds + rest_folds):
             pool = FoldModelsHandler._create_pool(fold_file, self._thread_count)
 
             for case, case_models in grouped_by_case_models.items():
@@ -78,8 +81,12 @@
                 calcers = metric_calcers[case]
 
                 for model_num, model in enumerate(case_models):
-                    if file_num != model_num:
-                        calcers[model_num].add(pool)
+                    if time_split_mode:
+                        if file_num <= (model_num + len(skipped_folds)):
+                            continue
+                    elif file_num == (model_num + len(skipped_folds)):
+                        continue
+                    calcers[model_num].add(pool)
 
         for case, case_models in grouped_by_case_models.items():
             calcers = metric_calcers[case]
@@ -104,7 +111,10 @@
                                     "Check eval_feature set and ignored features options".format(ignored_features))
         get_eval_logger().debug('Learn model {} on fold #{}'.format(str(case), fold_id))
         cur_time = time.time()
-        instance = CatBoost(params=case.get_params())
+        params=case.get_params()
+        if time_split_mode:
+            params['has_time']=True
+        instance = CatBoost(params=params)
         instance.fit(pool)
         instance.save_model(fname=model_path)
 
Index: catboost/eval/_splitter.py
===================================================================
--- catboost/eval/_splitter.py	(revision 4231722)
+++ catboost/eval/_splitter.py	(working copy)
@@ -9,7 +9,9 @@
 from ._fold_storage import FoldStorage
 from ._fold_storage import _FoldFile
 
+time_split_mode = True
 
+
 class _Splitter(object):
     """
      Splitter needs providing some parameters to create folds and some "reader",
@@ -51,11 +53,22 @@
                 count_groups, fold_size, self._min_folds_count)
             )
 
-        permutation = sorted(self._groups_ids)
-        self._random.shuffle(permutation)
+        if time_split_mode:
+            permutation = [self._line_groups_ids[0]]
+            for group_id in self._line_groups_ids[1:]:
+                if group_id != permutation[-1]:
+                    permutation.append(group_id)
+        else:
+            permutation = sorted(self._groups_ids)
+            self._random.shuffle(permutation)
 
         result = []
-        current_count_folds = min(count_groups // fold_size, left_folds)
+        current_count_folds = min(count_groups // fold_size - (1 if time_split_mode else 0), left_folds)
+        if current_count_folds == 0:
+            raise AttributeError('The size of fold is too big for time split: count_groups: {}, fold_size: {}.'.format(
+                count_groups, fold_size)
+            )
+        
         for i in range(current_count_folds):
             result.append(set(permutation[i * fold_size: (i + 1) * fold_size]))
         return result
```

**Comment by andrey-khropov** [comment]
> Hello!
> 
> It's been long time, since our last conversation. How is it going with eval tests? Is there anything I can do?

It has been more complicated than I've initially thought and I've been busy with other issues. The tests are available now, so I'll try to merge this PR.

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Kim2212, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: [794954](https://a.yandex-team.ru/review/794954)

**Comment by Kim2212** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by arcadia-devtools** [comment]
Check [794954](https://a.yandex-team.ru/review/794954) failed: 16 test(s) broken

**Comment by andrey-khropov** [comment]
Some tests have failed in the attempt to integrate this change to the catboost master branch.

The issues are the following:

1. Code style:

```
arcadia/catboost/python-package/catboost/eval/_fold_models_handler.py:112:15: E225 missing whitespace around operator
        params=case.get_params()
              ^
arcadia/catboost/python-package/catboost/eval/_fold_models_handler.py:114:31: E225 missing whitespace around operator
            params['has_time']=True
                              ^
```

2. Regression tests for eval features with eval_mode=SeqAddAndAll fail with a diff in the result:

test.py::test_eval_features[CPU-problem=binclass-eval_type=SeqAddAndAll]:

```
Test results differ from canonical:
files content differs:
Diff at root ["AUC"] ["Overfit iter diff"] ["{}"] : Doubles differ greater than limit: left: 4, right: 1, diff limit: 0
```

test.py::test_eval_features[CPU-problem=multiclass-eval_type=SeqAddAndAll]:

```
Test results differ from canonical:
files content differs:
Diff at root ["Accuracy"] ["Overfit iter diff"] ["{}"] : Doubles differ greater than limit: left: 8.5, right: 2, diff limit: 0
```

test.py::test_eval_features[CPU-problem=ranking-eval_type=SeqAddAndAll]:

```
Test results differ from canonical:
files content differs:
Diff at root ["QueryRMSE"] ["Overfit iter diff"] ["{}"] : Doubles differ greater than limit: left: -6.5, right: -5.5, diff limit: 0
```

test.py::test_eval_features[CPU-problem=regression-eval_type=SeqAddAndAll]:

```
Test results differ from canonical:
files content differs:
Diff at root ["RMSE"] ["Overfit iter diff"] ["{}"] : Doubles differ greater than limit: left: -0.5, right: -7, diff limit: 0
```

You can run tests for the python package the following way:

```
$ cd <checkout_root>/catboost/python-package/ut/medium
$ ../../../../ya make -t -A
```
To run not all tests but only a selected subset use ``-F`` flag like this:
 
```
$ cd <checkout_root>/catboost/python-package/ut/medium
$ ../../../../ya make -t -A -F test.py::test_eval_features*
```

As your changes affect only eval code it should be sufficient to run only ```test_eval_features``` and ```test_str_eval_metrics_in_eval_features``` tests.

The source code for tests is here: https://github.com/catboost/catboost/blob/a64bdc2526487a4a496221b57605083ebaa3280c/catboost/python-package/ut/medium/test.py#L4202 

Do not add ya make flags like 'USE_ARCADIA_PYTHON=no', 'USE_SYSTEM_PYTHON', 'OS_SDK=local' like described in the build instructions [here](https://catboost.ai/docs/installation/python-installation-method-build-from-source-linux-macos.html) though. They do not work with the tests now.

It would be also useful if you add new tests for time_split_mode.

**Comment by annaveronika** [comment]
It looks like we'll not finish this one. @Kim2212 if you will have news, let us know here in comments!

**Pull request closed without merging**
