### PR TITLE
Added the title

### PR DESCRIPTION
**Pull request by elenaspb2019**
Added the title, fixed the order

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

### CODE REVIEW

**Comment by elenaspb2019** [comment]
> hi @elenaspb2019 !!! glad to see you here handshake and thank you so much for this PR rose rose rose could you please sign the Yandex CLA https://catboost.ai/en/docs/concepts/development-and-contributions#yandex-cla ? this is formally needed to merge your PR...

Hello Evgueni! Sure, I did it above.  Thank you for reminding :)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@elenaspb2019 
according to [CONTRIBUTING.md](https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md) we need a formal statement from you as follows

image

**Comment by elenaspb2019** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request created: [3187704](https://a.yandex-team.ru/review/3187704)

**Comment by andrey-khropov** [comment]
Auto closing of merged PRs has been broken, so I have to close it manually.

**Pull request closed without merging**
