### PR TITLE
eval_set= must be added due to API changes for PySpark to work

### PR DESCRIPTION
**Pull request by adielsa**
+ solve compile error due to api change by adding eval_set= at fit()
+ update call to newer spark package

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@adielsa, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [2738455](https://a.yandex-team.ru/review/2738455)

**Comment by adielsa** [comment]
Approve

**Pull request merged**
