### PR TITLE
Node package for CatBoost model inference

### PR DESCRIPTION
**Pull request by IKholopov**
https://github.com/catboost/catboost/issues/1592

This the initial PR creating a node-package directory and providing the basic implementation of bindings to CatBoost C API.
For usage examples check out README.md.

Dependencies: node-addon-api (C++ wrapper of N-API)
Development dependencies: TypeScript, @types/node.

It does include some ad hock solutions, which make this package not yet suitable for publishing in NPM repository, namely:
- Use of bash scripts for building a package.
- Building from source on every installation from tarball/npm repo (`npm install catboost-model.tar.gz`), as the shared `model_interface` library binary is only released for Windows (at the moment).

Those issues are to be addressed in the upcoming PRs.

--

I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/](https://yandex.ru/legal/cla/).

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1695407](https://a.yandex-team.ru/review/1695407)

**Comment by arcadia-devtools** [comment]
Check [1695407](https://a.yandex-team.ru/review/1695407) passed

**Pull request merged**
