### PR TITLE
[ISSUE#1146] Adding exact SHAP values calculation

### PR DESCRIPTION
**Pull request by LordProtoss**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
Exact type of calculation for non-oblivious trees isn't implemented yet.

### CODE REVIEW

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request created: [1238031](https://a.yandex-team.ru/review/1238031)

**Comment by arcadia-devtools** [comment]
Check [1238031](https://a.yandex-team.ru/review/1238031) failed: 25 test(s) broken

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [1238031](https://a.yandex-team.ru/review/1238031)

**Comment by arcadia-devtools** [comment]
Check [1238031](https://a.yandex-team.ru/review/1238031) passed

**Pull request merged**
