### PR TITLE
Fstr sage values

### PR DESCRIPTION
**Pull request by igormarkov00**
Implementation of effective SAGE values calculation algorithm

### CODE REVIEW

**Comment by igormarkov00** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request created: [2771245](https://a.yandex-team.ru/review/2771245)

**Comment by andrey-khropov** [comment]
This PR has been merged in https://github.com/catboost/catboost/commit/54672013c558399001329b7ccea0fe5ca7689e5a

**Pull request closed without merging**
