### PR TITLE
feat: add github link prefix for UI edit button

### PR DESCRIPTION
**Pull request by yndx-birman**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

### CODE REVIEW

**Comment by yndx-birman** [comment]
@arcadia-devtools Ship it!

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [2006712](https://a.yandex-team.ru/review/2006712)

**Pull request merged**
