### PR TITLE
statistics about train Dataset is added

### PR DESCRIPTION
**Pull request by brazhenko**

### CODE REVIEW

**Comment by kizill** [comment]
Очень много мусорных файлов, нужно подчистить и сквошнуть изменения

**Comment by annaveronika** [comment]
please agree to our cla, see examples in other pr-s

**Comment by annaveronika** [comment]
@brazhenko Do you plan to proceed with the pr?

**Comment by brazhenko** [comment]
@annaveronika What do you mean?

**Comment by annaveronika** [comment]
@brazhenko I see - you removed the not needed files, thanks! You need now to agree to the cla, otherwise we cannot merge the code. You can write it in description of the pr.

**Comment by brazhenko** [comment]
@annaveronika I hope i did right. Comment is added.

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: 727740

**Pull request merged**
