### PR TITLE
[node-package] Migrate node-package to node scripts and downloading pre-built binaries

### PR DESCRIPTION
**Pull request by IKholopov**
#1592

1. Removed all build shell scripts, their functionality is not covered by `./build_scripts/` Node scripts.
2. Instead of downloading and building a source file, downloading a prebuilt binary from GitHub with a checksum check.
3. Added command `npm run prepublish` -  generates config with checksums for published binaries and prepares the required headers. This command should be ran before publishing the package via `npm publish` command.

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1746384](https://a.yandex-team.ru/review/1746384)

**Comment by arcadia-devtools** [comment]
Check [1746384](https://a.yandex-team.ru/review/1746384) passed

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request updated: [1746384](https://a.yandex-team.ru/review/1746384)

**Comment by arcadia-devtools** [comment]
Check [1746384](https://a.yandex-team.ru/review/1746384) passed

**Pull request merged**
