### PR TITLE
[R] return required tag Author in DESCRIPTION

### PR DESCRIPTION
**Pull request by ebalukova**
I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=ru).

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1709696](https://a.yandex-team.ru/review/1709696)

**Comment by arcadia-devtools** [comment]
Check [1709696](https://a.yandex-team.ru/review/1709696) passed

**Pull request merged**
