### PR TITLE
Tutorial on categorical features parameters. 

### PR DESCRIPTION
**Pull request by garkavem**

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1339051](https://a.yandex-team.ru/review/1339051)

**Comment by arcadia-devtools** [comment]
Check [1339051](https://a.yandex-team.ru/review/1339051) passed

**Pull request merged**
