### PR TITLE
Fix invalid wheel name

### PR DESCRIPTION
**Pull request by tim-habitat**
I believe this will close https://github.com/catboost/catboost/issues/2331

### CODE REVIEW

**Comment by escote-tatari** [comment]
https://github.com/python-poetry/poetry/issues/7692#issuecomment-1476567941

This is where the Poetry folks call out the exact line in the wheel code to fix this issue.

**Comment by escote-tatari** [comment]
https://github.com/catboost/catboost/blob/26cae4a03dd8f6d393adf011e9ff4fad4a49e96a/catboost/python-package/mk_wheel.py#L237 :eyes:

**Review by escote-tatari — APPROVED** [review]
:shipit:

**Comment by tim-habitat** [comment]
Hi, @andrey-khropov as seems you have write access, can you have a look at this pr ?

**Comment by tipanverella** [comment]
Could we please do this pull request?

**Comment by VGODIE** [comment]
looking forward for updates

**Comment by andrey-khropov** [comment]
> Hi, @andrey-khropov as seems you have write access, can you have a look at this pr ?

Sorry for the delayed response. 

- You'll have to agree with [the terms of CLA](https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md) first.
- I can merge this PR after that but most likely that won't be needed as we've switched to Python's standard build/installation scheme with pyproject.toml + setup.py instead of custom mk_wheel.py - #2278. I've checked that wheels built with the new scheme can be successfully installed by poetry.

**Comment by tim-habitat** [comment]
@andrey-khropov 
ah ok great ! well up to you if you want to merge it then. 

in either case, here's my agreement;

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Pull request closed without merging**
