### PR TITLE
Added shap interaction values

### PR DESCRIPTION
**Pull request by IvanKozlov98**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

### CODE REVIEW

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request created: [1198805](https://a.yandex-team.ru/review/1198805)

**Comment by arcadia-devtools** [comment]
Check [1198805](https://a.yandex-team.ru/review/1198805) failed: 41 build(s) broken, 53 test(s) broken

**Comment by mdjabc** [comment]
> @ arcadia-devtools发货！

Does it also having problem? Because the shap interaction values calculated by the catboost is nan

**Pull request merged**
