### PR TITLE
Task 12. adding new options for output

### PR DESCRIPTION
**Pull request by towelenee**
WIP
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by Noxoomo** [comment]
@arcadia-devtools Ship It!

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 701505

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 701589

**Comment by annaveronika** [comment]
test test_write_predictions_to_streams is failing:

catboost/pytest/test.py:6035: in test_write_predictions_to_streams
    yatest.common.execute(calc_cmd)
library/python/testing/yatest_common/yatest/common/process.py:442: in execute
    res.wait(check_exit_code, timeout, on_timeout)
library/python/testing/yatest_common/yatest/common/process.py:308: in wait
    self._finalise(check_exit_code)
library/python/testing/yatest_common/yatest/common/process.py:315: in _finalise
    raise ExecutionError(self)
E   ExecutionError: Command 'https://proxy.sandbox.yandex-team.ru/824860380/build-release/catboost.tar/catboost/app/catboost calc --input-path arcadia/catboost/pytest/data/adult/test_small --column-description arcadia/catboost/pytest/data/adult/train.cd -m http://download-distbuild.n.yandex-team.ru/mds/192583/results_merger-11291198702365356620-0-5AC-528474/catboost/pytest/test-results/catboost-pytest/default-linux-x86_64-release-ALLOCATOR%3DLF-DEBUGINFO_LINES_ONLY%3Dyes-NO_DEBUGINFO%3Dno-TRAVERSE_RECURSE_FOR_TESTS%3Dyes-USE_EAT_MY_DATA%3Dyes-asan/testing_out_stuff.tar/2/testing_out_stuff/test.py.test_write_predictions_to_streams/model.bin --output-path stream://stdout > http://download-distbuild.n.yandex-team.ru/mds/192583/results_merger-11291198702365356620-0-5AC-528474/catboost/pytest/test-results/catboost-pytest/default-linux-x86_64-release-ALLOCATOR%3DLF-DEBUGINFO_LINES_ONLY%3Dyes-NO_DEBUGINFO%3Dno-TRAVERSE_RECURSE_FOR_TESTS%3Dyes-USE_EAT_MY_DATA%3Dyes-asan/testing_out_stuff.tar/2/testing_out_stuff/test.py.test_write_predictions_to_streams/calc_test.eval' has failed with code 1.
E   Errors:
E   (NLastGetopt::TUsageException) library/getopt/small/last_getopt_parser.cpp:69: required exactly 0 free args
E   Try 'https://proxy.sandbox.yandex-team.ru/824860380/build-release/catboost.tar/catboost/app/catboost calc --help' for more information.

**Comment by annaveronika** [comment]
And pep8 check says:
```
arcadia/catboost/pytest/test.py:6009:1: E302 expected 2 blank lines, found 1
def test_write_predictions_to_streams():
^
arcadia/catboost/pytest/test.py:6013:1: W293 blank line contains whitespace

^
arcadia/catboost/pytest/test.py:6051:1: W293 blank line contains whitespace

^
arcadia/catboost/pytest/test.py:6051:1: W391 blank line at end of file

^
```

**Comment by towelenee** [comment]
@annaveronika Why would yatest.common.test_output_path('calc_test.eval') create a http address?

**Comment by annaveronika** [comment]
This pull request was accidentally merged (its first version). Could you please create one more pr, and we'll discuss all questions there?

**Comment by annaveronika** [comment]
yatest.common.test_output_path('calc_test.eval') should create path to a local folder "testing_out_stuff" where files that you generate can be stored. It should not be http address.

**Comment by kizill** [comment]
This pull request is already nerged and i've fixed tests during internal merge with GitHub. There is nothing to do in this PR now. Thank you a lot for your help!

**Pull request merged**
