### PR TITLE
Fixup for MSVC 14.28 compilator bug. Fixes #1735 Fixes #1761 Fixes #1197

### LINKED ISSUE #1197: Dying kernel on Jupiter notebook
Problem: After run model.fit() (CatBoostClassifier) in jupiter notebook i got message "The kernel appears to have died. It will restart automatically.". Its happens also on tutorial https://github.com/catboost/tutorials/blob/master/python_tutorial.ipynb
Re-installing anaconda don't solve problem.

catboost version: 0.22 (same problem 0.21)
Operating System:  Windows 10 Corporate LTSC
CPU: Intel(R) Core(TM)2 Quad_CPU 8400 2.66GHz

### LINKED ISSUE #1735: Kernel dying when I execute with GPU
Problem: "Error: kernel connection broken"
catboost version: 0.26 
Operating System: Windows 10
CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz
GPU: NVIDIA Quadro T1000
CUDA toolkit: 11.3.1

Hi! I'm running a classification model on CatBoost but when I try to execute it with task_type = 'GPU' a message appear saying the kernel connection is broken. If I execute it with CPU I don't have any problem.

At the begining I saw on the task manager the GPU memory was at 100% and I tried limitation the usage but the error persist.

The error appears after 600 hundred of iterations (more or less). The details of my model are:

    model = CatBoostClassifier(
        iterations = 100000
        , learning_rate = 0.025
        , verbose = 2500
        , early_stopping_rounds = 1000
        , cat_features = cat_col
        , loss_function = "Logloss"
        , eval_metric = "F1"
        , task_type = "GPU"
        , gpu_ram_part = 0.75
        , depth = 8
        , border_count = 32
        , max_ctr_complexity = 2
        , random_seed = 42
    )
    model.fit(
        train_pool
        , eval_set = val_pool
        , plot = False
    )

### LINKED ISSUE #1761: catboost 0.26 GPU R code throws an error.
### System Info.

* catboost version: 0.26
* Operating System: Windows10
* CPU: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
* GPU: GeForce RTX 2080 SUPER with driver version 465.42

I was trying to run the GPU test R code on the website on my system but 0.26 version throw an error and crashed! I switched to 0.25.1 version (as the website recommends) it works!

```{r}
library(catboost)

countries = as.factor(c('RUS','USA','SUI')) 
years = c(1900,1896,1896)
phone_codes = c(7,1,41)
domains = as.factor(c('ru','us','ch'))

dataset = data.frame(countries, years, phone_codes, domains)

label_values = c(0,1,1)

fit_params <- list(iterations = 100,
                   loss_function = 'Logloss',
                   ignored_features = c(4,9),
                   border_count = 32,
                   depth = 5,
                   learning_rate = 0.03,
                   l2_leaf_reg = 3.5,
                   task_type = 'GPU')

pool = catboost.load_pool(dataset, 
                          label = label_values, 
                          cat_features = c(0,3))

model <- catboost.train(pool, params = fit_params)

```

### PR DESCRIPTION
**Pull request by kizill**
Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1868761](https://a.yandex-team.ru/review/1868761)

**Comment by arcadia-devtools** [comment]
Check [1868761](https://a.yandex-team.ru/review/1868761) failed: 10 build(s) broken, 1 test(s) broken

**Pull request merged**
