### PR TITLE
Model shrink rate interaction

### PR DESCRIPTION
**Pull request by Andrew-Angrew**
1. Set default value for model_shrink_rate to 0.2 when monotone constraints is not empty .
2. Reset model_shrink_rate to zero if baseline or init_model is present.
3. Fix shrinkage in combination with boosting from average.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [943379](https://a.yandex-team.ru/review/943379)

**Comment by arcadia-devtools** [comment]
Check [943379](https://a.yandex-team.ru/review/943379) failed: 1 test(s) broken

**Pull request merged**
