### PR TITLE
Add mljar-supervised to AWESOME list

### PR DESCRIPTION
**Pull request by pplonski**
The CatBoost is used a lot in [mljar-supervised](https://github.com/mljar/mljar-supervised) AutoML package! Thanks for making it! :)

I hereby agree to the terms of the CLA available at: [link]( https://yandex.ru/legal/cla/?lang=en).

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1256919](https://a.yandex-team.ru/review/1256919)

**Comment by arcadia-devtools** [comment]
Check [1256919](https://a.yandex-team.ru/review/1256919) passed

**Pull request merged**
