### PR TITLE
Leaf indexes tutorial

### PR DESCRIPTION
**Pull request by Andrew-Angrew**
I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=en)

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [817609](https://a.yandex-team.ru/review/817609)

**Comment by arcadia-devtools** [comment]
Check [817609](https://a.yandex-team.ru/review/817609) passed

**Pull request merged**
