### PR TITLE
Added GPU evaluation (fixed issue 972)

### PR DESCRIPTION
**Pull request by rakalexandra**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1786378](https://a.yandex-team.ru/review/1786378)

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request updated: [1786378](https://a.yandex-team.ru/review/1786378)

**Pull request merged**
