### PR TITLE
Added dotnet compatibility with UNIX

### PR DESCRIPTION
**Pull request by khanova**

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1249538](https://a.yandex-team.ru/review/1249538)

**Comment by arcadia-devtools** [comment]
Check [1249538](https://a.yandex-team.ru/review/1249538) passed

**Pull request merged**
