### PR TITLE
5 add flag not copied unnecessarily

### PR DESCRIPTION
**Pull request by sharaalfa**
Before submitting a pull request, please do the following steps:

1. Read instructions for contributors [here](https://tech.yandex.com/catboost/doc/dg/concepts/development-and-contributions-docpage/).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the CLA.
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by annaveronika** [comment]
There are a lot of files that should not be a part of this pr. Please remove them

**Comment by annaveronika** [comment]
Please agree to our CLA, see examples how to do it in other pr-s.

**Comment by sharaalfa** [comment]
@annaveronika open

**Comment by sharaalfa** [comment]
5\. I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en.

**Comment by annaveronika** [comment]
Please close one of the two pr-s and add changes to the one that is opened. Any of them - which ever you like. We don't need two pr-s with the same change :)

**Pull request closed without merging**
