### PR TITLE
add hyperparameters tuning tutorial

### PR DESCRIPTION
**Pull request by Atygayev**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1779243](https://a.yandex-team.ru/review/1779243)

**Comment by arcadia-devtools** [comment]
Check [1779243](https://a.yandex-team.ru/review/1779243) passed

**Pull request merged**
