### PR TITLE
class_weights in grid_search and randomized_search

### PR DESCRIPTION
**Pull request by vazgenk**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1167460](https://a.yandex-team.ru/review/1167460)

**Comment by arcadia-devtools** [comment]
Check [1167460](https://a.yandex-team.ru/review/1167460) passed

**Pull request merged**
