### PR TITLE
fix unnecessary computation of leaf indexes for test data.

### PR DESCRIPTION
**Pull request by Andrew-Angrew**

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1105381](https://a.yandex-team.ru/review/1105381)

**Comment by arcadia-devtools** [comment]
Check [1105381](https://a.yandex-team.ru/review/1105381) passed

**Pull request merged**
