### PR TITLE
Load Json model format in Java Client

### PR DESCRIPTION
**Pull request by timotta**
I hereby agree to the terms of the CLA available at: https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md

This PR enables loading CatBoost Json model format in the Java Client Library.

My intention is to use CatBoost in the LTR Elasticsearch plugin as an alternative to XGBoost. But for doing that it's needed to loading the json model since LTR plugin saves the model as json in Elasticsearch.

Example usage:

```java
import ai.catboost.CatBoostError;
import ai.catboost.CatBoostModel;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class CatBoostRanker {
    public static void main(String[] args) {
        try {
            final String f = "/home/tiago.motta/Projetos/ltr/catboost_model.json";
            final CatBoostModel catBoostModelByFile = CatBoostModel.loadModel(f, "json");

            final InputStream in = new FileInputStream(f);
            final CatBoostModel catBoostModelByStream = CatBoostModel.loadModel(in, "json");

            System.out.println("=====================================");
            System.out.println(catBoostModelByFile);
            System.out.println(catBoostModelByStream);
            System.out.println("=====================================");

        } catch (CatBoostError | IOException catBoostError) {
            catBoostError.printStackTrace();
        }
    }
}
```

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1717394](https://a.yandex-team.ru/review/1717394)

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request updated: [1717394](https://a.yandex-team.ru/review/1717394)

**Comment by andrey-khropov** [comment]
This PR has been merged in https://github.com/catboost/catboost/commit/8beda769c273542f1106e2f590b0fc9f93031567, unfortunately our robot marks it as closed, not as merged.

**Pull request closed without merging**
