### PR TITLE
Divide mldotnet

### PR DESCRIPTION
**Pull request by khanova**
Divide CatBoostModel interface into two classes:
Cass with Microsoft.ML implementation
Class for predictions (without Microsoft.ML implementation)

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1249975](https://a.yandex-team.ru/review/1249975)

**Comment by arcadia-devtools** [comment]
Check [1249975](https://a.yandex-team.ru/review/1249975) passed

**Pull request merged**
