### PR TITLE
Update python-usages_examples.md

### PR DESCRIPTION
**Pull request by cyprienc**
Hello,

It seemed to me that the batch training example had a typo. The baseline for the second batch should be the predictions of the first model for the second batch instead of the first batch. Let me know if this is not true.
Thanks.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [2946637](https://a.yandex-team.ru/review/2946637)

**Comment by cyprienc** [comment]
> @cyprienc, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

Done. Thanks.

**Comment by cyprienc** [comment]
@kizill - hi - what's required for this to be merged? thanks.

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Pull request closed without merging**
