### PR TITLE
[node-package] Move base e2e-test image

### PR DESCRIPTION
**Pull request by IKholopov**
Moved e2e-test image to removed extra supply chain dependencies

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1779476](https://a.yandex-team.ru/review/1779476)

**Comment by arcadia-devtools** [comment]
Check [1779476](https://a.yandex-team.ru/review/1779476) passed

**Pull request merged**
