### PR TITLE
Renamed  Custom to UserDefined and Added more information about error wh...

### PR DESCRIPTION
**Pull request by Danyago98**
Now Custom type has name PythonUserDefinedPerObject. Also when number of features in training and validation sets differs, you will see more informative error.

____
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 709155

**Comment by annaveronika** [comment]
The build is broken:

```
$(SOURCE_ROOT)/catboost/libs/options/catboost_options.cpp:459:29: error: no member named 'Custom' in 'ELossFunction'
        case ELossFunction::Custom: {
             ~~~~~~~~~~~~~~~^
1 error generated.
```

```
In file included from $(SOURCE_ROOT)/catboost/cuda/targets/multiclass_targets.cpp:1:
$(SOURCE_ROOT)/catboost/cuda/targets/multiclass_targets.h:159:45: error: no member named 'Custom' in 'ELossFunction'
        ELossFunction Type = ELossFunction::Custom;
                             ~~~~~~~~~~~~~~~^
$(SOURCE_ROOT)/catboost/cuda/targets/multiclass_targets.h:159:23: error: private field 'Type' is not used [-Werror,-Wunused-private-field]
        ELossFunction Type = ELossFunction::Custom;
                      ^
2 errors generated.
```

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: 735256

**Comment by andrey-khropov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@andrey-khropov, internal review request created: 735302

**Pull request merged**
