### PR TITLE
fix(docs): change to the new is_fitted() API

### PR DESCRIPTION
**Pull request by davydof**

### CODE REVIEW

**Comment by annaveronika** [comment]
Thanks a lot for the fix!

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@davydof, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [868892](https://a.yandex-team.ru/review/868892)

**Comment by arcadia-devtools** [comment]
Check [868892](https://a.yandex-team.ru/review/868892) passed

**Comment by davydof** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Pull request merged**
