### PR TITLE
Fix EvalMetricsResult.get_metric()

### PR DESCRIPTION
**Pull request by Roffild**
Mini fix.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Roffild, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1709695](https://a.yandex-team.ru/review/1709695)

**Comment by arcadia-devtools** [comment]
Check [1709695](https://a.yandex-team.ru/review/1709695) passed

**Comment by Roffild** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

**Pull request merged**
