### PR TITLE
[R] Update documentation per CRAN requirements

### PR DESCRIPTION
**Pull request by jameslamb**
Based on https://github.com/catboost/catboost/issues/439#issuecomment-762983571, this PR proposes some fixes for the R package's documentation. This PR resolves several issues found by `R CMD check`, which would prevent the package from acceptance on CRAN.

## Changes in this pull request

**1. `DESCRIPTION` issues**

```text
* checking DESCRIPTION meta-information ... NOTE
Authors@R field gives no person with maintainer role, valid email
address and non-empty name.
Author field differs from that derived from Authors@R
  Author:    ‘CatBoost DevTeam [aut, cre]’
  Authors@R: ‘Nikita Dmitriev [aut], Andrey Gulin [aut] (Chief researcher, author of the algorithm and of the first implementation), Anna Veronika Dorogush [aut], Stanislav Kirillov [aut], Victor Omelyanenko [aut], Evgueni Petrov [aut], Andrey Mishenko [aut], Pavel Kalinin [aut], Vyacheslav Alipov [aut], Egor Samosvat [aut], Alexander Kobotov [aut], Dmitry Schelchkov [aut], Vasily Ershov [aut] (GPU implementation), Vyacheslav Murashkin [aut] (R Package), Roman Nefyodov [aut] (R Package), Anastasia Bezzubtseva [aut] (R Package), Alexey Gorchakov [aut] (R Package), Ivan Karev [aut] (Visualisation), Sergey Berezhnoy [aut] (Visualisation), Roman Rybalchenko [aut] (Visualisation), Valeriy Babushkin [aut] (Tutorials), Mikhail Pershin [aut] (Tutorials), Emil Kayumov [aut] (Tutorials), Evgeny Eltyshev [aut] (Tutorials), Alexander Baranov [aut] (CoreML support), Dmitry Oganesyan [aut] (R Package), CatBoost DevTeam [cph], WLOG Solutions [ctb] (R package preparation for CRAN submission), Dmitry Baksheev [aut, cre]’

Maintainer field differs from that derived from Authors@R
  Maintainer: ‘Stanislav Kirillov <staskirillov@gmail.com>’
  Authors@R:  ‘’
```

These errors come from the fact that the package currently has an `Authors@R` and fields `Maintainer:` and `Author:`. If you have `Authors@R`, fields `Maintainer:` and `Author:` will be automatically generated by `R CMD build`.

**2. Missing `@return`, `@title`, `@name`, `@description`**

```text
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

These issues can be caused by missing entries for name, title, description, or return. This PR adds them.

**3. Typos**

```text
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'catboost.get_object_importance'
  ‘type’
Documented arguments not in \usage in documentation object 'catboost.get_object_importance':
  ‘type.’
```

This was just a type, an entry with `#' @param type.`. I fixed that, and a few other small typos.

I searched for other typos with this code

```shell
cat catboost/R-package/R/*.R | aspell list | sort t-u
```

## How to test this

From the `catboost/R-package` directory, you can run the following to build and check the package.

```shell
R CMD BUILD .
R CMD check --as-cran catboost_0.24.4.tar.gz
```

<details><summary>R CMD check logs before this PR (2 ERRORs, 1 WARNING, 4 NOTEs)</summary>

```text
* using log directory ‘/Users/jlamb/repos/catboost/catboost/R-package/catboost.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘catboost/DESCRIPTION’ ... OK
* this is package ‘catboost’ version ‘0.24.4’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Stanislav Kirillov <staskirillov@gmail.com>’

New submission
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘catboost’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 28.5Mb
  sub-directories of 1Mb or more:
    libs  28.1Mb
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... NOTE
Authors@R field gives no person with maintainer role, valid email
address and non-empty name.
Author field differs from that derived from Authors@R
  Author:    ‘CatBoost DevTeam [aut, cre]’
  Authors@R: ‘Nikita Dmitriev [aut], Andrey Gulin [aut] (Chief researcher, author of the algorithm and of the first implementation), Anna Veronika Dorogush [aut], Stanislav Kirillov [aut], Victor Omelyanenko [aut], Evgueni Petrov [aut], Andrey Mishenko [aut], Pavel Kalinin [aut], Vyacheslav Alipov [aut], Egor Samosvat [aut], Alexander Kobotov [aut], Dmitry Schelchkov [aut], Vasily Ershov [aut] (GPU implementation), Vyacheslav Murashkin [aut] (R Package), Roman Nefyodov [aut] (R Package), Anastasia Bezzubtseva [aut] (R Package), Alexey Gorchakov [aut] (R Package), Ivan Karev [aut] (Visualisation), Sergey Berezhnoy [aut] (Visualisation), Roman Rybalchenko [aut] (Visualisation), Valeriy Babushkin [aut] (Tutorials), Mikhail Pershin [aut] (Tutorials), Emil Kayumov [aut] (Tutorials), Evgeny Eltyshev [aut] (Tutorials), Alexander Baranov [aut] (CoreML support), Dmitry Oganesyan [aut] (R Package), CatBoost DevTeam [cph], WLOG Solutions [ctb] (R package preparation for CRAN submission), Dmitry Baksheev [aut, cre]’

Maintainer field differs from that derived from Authors@R
  Maintainer: ‘Stanislav Kirillov <staskirillov@gmail.com>’
  Authors@R:  ‘’

* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'catboost.get_object_importance'
  ‘type’
Documented arguments not in \usage in documentation object 'catboost.get_object_importance':
  ‘type.’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/Users/jlamb/repos/catboost/catboost/R-package/catboost.Rcheck/catboost/libs/libcatboostr.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
  Found ‘__exit’, possibly from ‘_exit’ (C)
  Found ‘_abort’, possibly from ‘abort’ (C)
  Found ‘_exit’, possibly from ‘exit’ (C)
  Found ‘_printf’, possibly from ‘printf’ (C)
File ‘catboost/libs/libcatboostr.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
It is good practice to register native routines and to disable symbol
search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... ERROR
Running examples in ‘catboost-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: catboost.load_pool
> ### Title: Create a dataset
> ### Aliases: catboost.load_pool
> 
> ### ** Examples
> 
> # From file
> pool_path <- system.file("extdata", "adult_train.1000", package = "catboost")
> cd_path <- system.file("extdata", "adult.cd", package = "catboost")
> pool <- catboost.load_pool(pool_path, column_description = cd_path)
> head(pool)
Error in head.catboost.Pool(pool) : 
  catboost/R-package/src/catboostr.cpp:388: Cannot slice non-numeric features data
Calls: head -> head.catboost.Pool
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  ERROR (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  FAILURE (test_model.R:235:3): model: baseline
  ERROR (test_pool.R:201:3): pool: nan
  Warning (test_pool.R:214:3): pool: data.frame vs dplyr::tbl_df vs pool
  ERROR (test_pool.R:226:3): pool: data.frame vs dplyr::tbl_df vs pool
  
  [ FAIL 4 | WARN 7 | SKIP 0 | PASS 46 ]
  Error: Test failures
  Execution halted
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 2 ERRORs, 1 WARNING, 4 NOTEs
```

</details>

<details><summary>R CMD check logs as of this PR (2 ERRORs, 3 NOTEs)</summary>

```text
* using log directory ‘/Users/jlamb/repos/catboost/catboost/R-package/catboost.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘catboost/DESCRIPTION’ ... OK
* this is package ‘catboost’ version ‘0.24.4’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Stanislav Kirillov <staskirillov@gmail.com>’

New submission
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘catboost’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 28.5Mb
  sub-directories of 1Mb or more:
    libs  28.1Mb
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/Users/jlamb/repos/catboost/catboost/R-package/catboost.Rcheck/catboost/libs/libcatboostr.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
  Found ‘__exit’, possibly from ‘_exit’ (C)
  Found ‘_abort’, possibly from ‘abort’ (C)
  Found ‘_exit’, possibly from ‘exit’ (C)
  Found ‘_printf’, possibly from ‘printf’ (C)
File ‘catboost/libs/libcatboostr.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
It is good practice to register native routines and to disable symbol
search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... ERROR
Running examples in ‘catboost-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: catboost.load_pool
> ### Title: Create a dataset
> ### Aliases: catboost.load_pool
> 
> ### ** Examples
> 
> # From file
> pool_path <- system.file("extdata", "adult_train.1000", package = "catboost")
> cd_path <- system.file("extdata", "adult.cd", package = "catboost")
> pool <- catboost.load_pool(pool_path, column_description = cd_path)
> head(pool)
Error in head.catboost.Pool(pool) : 
  catboost/R-package/src/catboostr.cpp:388: Cannot slice non-numeric features data
Calls: head -> head.catboost.Pool
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  Warning (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  ERROR (test_caret_parameter_tuning.R:46:3): test caret train and parameter tuning on adult pool
  FAILURE (test_model.R:235:3): model: baseline
  ERROR (test_pool.R:201:3): pool: nan
  Warning (test_pool.R:214:3): pool: data.frame vs dplyr::tbl_df vs pool
  ERROR (test_pool.R:226:3): pool: data.frame vs dplyr::tbl_df vs pool
  
  [ FAIL 4 | WARN 7 | SKIP 0 | PASS 46 ]
  Error: Test failures
  Execution halted
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 2 ERRORs, 3 NOTEs
```

</details>

Thanks for your time and consideration.

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@jameslamb, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1646070](https://a.yandex-team.ru/review/1646070)

**Comment by jameslamb** [comment]
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en

**Comment by arcadia-devtools** [comment]
Pull request is not mergeable, will restore from internal repo

**Comment by jameslamb** [comment]
> Pull request is not mergeable, will restore from internal repo

@nikitxskv what does this mean and why was this PR closed?

**Comment by david-cortes** [comment]
@jameslamb : sorry, I also updated some docs and it resulted in a merge conflict.

**Comment by jameslamb** [comment]
> @jameslamb : sorry, I also updated some docs and it resulted in a merge conflict.

no problem, merge conflicts happen!

It's just disappointing to me that the way this works is "there was a merge conflict, so a bot commits instead". Because now my name isn't on that commit so it's like I lost credit for this contribution that I put time and energy into.

**Comment by kizill** [comment]
@jameslamb i think it's awful, we will fix this manually tomorrow in this repo:)

**Comment by jameslamb** [comment]
thanks very much!

**Comment by kizill** [comment]
Finally 87939eb82acbea5a4e0f8f335404907c1790b22a !

**Comment by jameslamb** [comment]
Thank you for doing that!

**Pull request closed without merging**
