### PR TITLE
Fix NameError when passing invalid type to get_feature_importance

### PR DESCRIPTION
**Pull request by rparrapy**

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@rparrapy, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by rparrapy** [comment]
I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=en](https://yandex.ru/legal/cla/?lang=en)

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
Check [1092207](https://a.yandex-team.ru/review/1092207) failed: 1056 test(s) broken

**Comment by annaveronika** [comment]
This pr breaks all the tests. To see the errors please run tests with command
`ya make -t` in the following folders:
catboost/python-package/ut/medium
catboost/libs/model/model_export/ut
catboost/pytest

**Comment by andrey-khropov** [comment]
There has been a race condition with this fix. The same change has already been merged in https://github.com/catboost/catboost/commit/838a445b6d59143f901dfdc43971cdc35cd6f89f

**Pull request closed without merging**
