### PR TITLE
PartialShuffle function

### PR DESCRIPTION
**Pull request by igormarkov00**
Implemented PartialShuffle function which fills first N elements of array with equiprobably randomly chosen elements of array with no replacement

### CODE REVIEW

**Comment by igormarkov00** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request created: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request updated: [2547385](https://a.yandex-team.ru/review/2547385)

**Pull request merged**
