### PR TITLE
aft+cox survival regression tutorial

### PR DESCRIPTION
**Pull request by blatr**
Hi!
This is tutorial for AFT and Cox loss functions which will were recently added in blatr/catboost#1629, fibersel/catboost#1624
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@ek-ak, internal review request created: [1788584](https://a.yandex-team.ru/review/1788584)

**Comment by arcadia-devtools** [comment]
Check [1788584](https://a.yandex-team.ru/review/1788584) passed

**Pull request merged**
