### PR TITLE
typo

### PR DESCRIPTION
**Pull request by Andrew-Angrew**
I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=ru].

### CODE REVIEW

**Comment by annaveronika** [comment]
Please agree to CLA, see examples in other pr-s.

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [783508](https://a.yandex-team.ru/review/783508)

**Comment by arcadia-devtools** [comment]
Check [783508](https://a.yandex-team.ru/review/783508) passed

**Pull request merged**
