### PR TITLE
UPD: shap calculation benchmark

### PR DESCRIPTION
**Pull request by canorbal**
Add: benchmark data preprocessing, asymptotic analysis
Upd: README.md in shap benchmark, speed_comparison.ipynb

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 646657

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 646665

**Comment by annaveronika** [comment]
@canorbal The change is on github now! Thanks a lot!!!

**Pull request merged**
