### PR TITLE
Fixed README.md markup

### PR DESCRIPTION
**Pull request by duketemon**
Fixed README.md markup

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@duketemon, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [836975](https://a.yandex-team.ru/review/836975)

**Comment by arcadia-devtools** [comment]
Check [836975](https://a.yandex-team.ru/review/836975) passed

**Comment by duketemon** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

**Comment by annaveronika** [comment]
Thanks a lot @duketemon!

**Pull request merged**
