### PR TITLE
[node-package] E2E deployment test for node-package

### PR DESCRIPTION
**Pull request by IKholopov**
#1592

Adding end-to-end package publication test. What it does is:
1. Creates a docker image with local npm registry (verdaccio) 
2. Publishes the package from source to this local registry
3. Installs it for a package with a simple test

Running docker is required to run this test.

### CODE REVIEW

**Comment by IKholopov** [comment]
@nikitxskv

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1761453](https://a.yandex-team.ru/review/1761453)

**Comment by arcadia-devtools** [comment]
Check [1761453](https://a.yandex-team.ru/review/1761453) passed

**Pull request merged**
