### PR TITLE
Added Independent Tree Shap

### PR DESCRIPTION
**Pull request by IvanKozlov98**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
Implementation of Independent Tree Shap algorithm from https://arxiv.org/abs/1905.04610v1.

### CODE REVIEW

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Ivan, thank you for your contribution!
Please use TSharedPtr or TAtomicSharedPtr (whichever is appropriate) instead of THolder in catboost/libs/fstr/shap_prepared_trees.h, line 37.
Currently, catboost/pytest cannot be built.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Please use ... = ... .Release() instead of std::move.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1300188](https://a.yandex-team.ru/review/1300188)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
Check [1300188](https://a.yandex-team.ru/review/1300188) failed: 6 build(s) broken, 47 test(s) broken

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1300188](https://a.yandex-team.ru/review/1300188)

**Comment by arcadia-devtools** [comment]
Check [1300188](https://a.yandex-team.ru/review/1300188) passed

**Pull request merged**
