### PR TITLE
Flag not copied unnecessarily with blank and whitespace

### PR DESCRIPTION
**Pull request by sharaalfa**
Before submitting a pull request, please do the following steps:

1. Read instructions for contributors [here](https://tech.yandex.com/catboost/doc/dg/concepts/development-and-contributions-docpage/).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the CLA.
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by annaveronika** [comment]
Please agree to our CLA (see examples in other pr-s).
Otherwise we will not be able to merge your pr.

**Comment by annaveronika** [comment]
Please remove the files that should not be part of the pr.

**Comment by kizill** [comment]
And i personally recommend to squash all changes unrelated changes and use feature branch rebase instead of merge to have clear commit history.

**Comment by annaveronika** [comment]
There is also a pr https://github.com/catboost/catboost/pull/663 with the same changes. Could you please close one of these two pr-s?

**Comment by annaveronika** [comment]
I've made comments on the pr https://github.com/catboost/catboost/pull/663. It's closed now, but I think the comments are relevant for this one alse.

**Comment by sharaalfa** [comment]
what comments? I made changes on my branch but I don't have access to make a pull request

**Comment by sharaalfa** [comment]
@annaveronika annaveronika what comments? I made changes on my branch but I don't have access to make a pull request

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/pull/663 - you can read them here.
In conversation tab.

**Comment by sharaalfa** [comment]
@annaveronika I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en. 
as well as I made changes on https://github.com/sharaalfa/catboost/tree/flag_not_copied_unnecessarily 
you can pick up from my branch I do not have access to make a pool call

**Comment by annaveronika** [comment]
The other pr is closed. Let's work in this pr, please add your changes here.

**Comment by sharaalfa** [comment]
@annaveronika i deleted and add CLA

**Comment by annaveronika** [comment]
Great! Now we need to add a new diff with fixes.

**Comment by sharaalfa** [comment]
@annaveronika okay

**Comment by andrey-khropov** [comment]
> > Great! Now we need to add a new diff with fixes.

> @annaveronika okay

Hello! Any progress on this?

**Comment by annaveronika** [comment]
@sharaalfa Hi, do you plan to commit the pr or we should discard it?

**Comment by sharaalfa** [comment]
@annaveronika Hi I am  fixed this

**Comment by sharaalfa** [comment]
@annaveronika  i am corrected test.py

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [741686](https://a.yandex-team.ru/review/741686)

**Comment by arcadia-devtools** [comment]
Check [741686](https://a.yandex-team.ru/review/741686) failed: 51 build(s) broken, 98 test(s) broken

**Comment by annaveronika** [comment]
The build is broken:
```
Error compiling Cython file:
------------------------------------------------------------
...
        else:
            if isinstance(data, np.ndarray) and data.dtype == np.float32:
                if data.flags.aligned and data.flags.f_contiguous:
                    do_use_raw_data_in_features_order = True
        if do_use_raw_data_in_features_order == False and sure_no_features_copy == True:
            raise CatboostError('No all methods that accept features data as parameters ensure that zero-copy implementation.')
                 ^
------------------------------------------------------------

catboost/python-package/catboost/_catboost.pyx:1973:18: undeclared name not builtin: CatboostError
```

**Comment by annaveronika** [comment]
@sharaalfa Do you plan to proceed with the pr?

**Comment by annaveronika** [comment]
closing because of inactivity

**Pull request closed without merging**
