### PR TITLE
[WIP] CatBoost Rust package

### PR DESCRIPTION
**Pull request by Shuternay**
In this PR I add rust crate which allows to apply catboost model from rust.

There are still some things to do:

1. Integrate tests with Arcadia build system. I suppose I should add simple python test which just runs rust tests?
2. Change contact information in package descriptions: catboost/rust-package/Cargo.toml and catboost/rust-package/catboost-sys/Cargo.toml.

I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=ru)

#473

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [802114](https://a.yandex-team.ru/review/802114)

**Comment by arcadia-devtools** [comment]
Check [802114](https://a.yandex-team.ru/review/802114) passed

**Comment by annaveronika** [comment]
@Shuternay Congrats! And thanks a lot for your contribution!

**Comment by annaveronika** [comment]
Btw we need documentation for the package, please take a look on Java docs, it should be similar to that: https://catboost.ai/docs/concepts/java-package.html

And we also need a tutorial in tutorials repo with a reproducible example how this package is used.

**Pull request merged**
