### PR TITLE
Fix of broken tests

### PR DESCRIPTION
**Pull request by khanova**
* Updated iris model
* Test datasets were saved in the directory. We do not need to download it
every time.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@khanova, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1200182](https://a.yandex-team.ru/review/1200182)

**Comment by arcadia-devtools** [comment]
Check [1200182](https://a.yandex-team.ru/review/1200182) passed

**Pull request merged**
