### PR TITLE
fix standalone_evaluator

### PR DESCRIPTION
**Pull request by dmitrySorokin**

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@dmitrySorokin, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1031975](https://a.yandex-team.ru/review/1031975)

**Comment by arcadia-devtools** [comment]
Check [1031975](https://a.yandex-team.ru/review/1031975) passed

**Comment by dmitrySorokin** [comment]
I hereby agree to the terms of the CLA available at: [https://yandex.ru/legal/cla/?lang=ru].

**Pull request merged**
