### PR TITLE
Rust package fixes

### PR DESCRIPTION
**Pull request by shuternay**
- Fix libcatboostmodel build flags.
- Update package readme.

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [814593](https://a.yandex-team.ru/review/814593)

**Comment by arcadia-devtools** [comment]
Check [814593](https://a.yandex-team.ru/review/814593) passed

**Pull request merged**
