### PR TITLE
refine tree visualization tutorial.

### PR DESCRIPTION
**Pull request by Andrew-Angrew**

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [818718](https://a.yandex-team.ru/review/818718)

**Comment by arcadia-devtools** [comment]
Check [818718](https://a.yandex-team.ru/review/818718) passed

**Pull request merged**
