### PR TITLE
Refactoring shaps

### PR DESCRIPTION
**Pull request by IvanKozlov98**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
This pr contain moving TShapPreparedTrees to new files and refactoting some files from catboost/libs/fstr/ related with calculation shap values.

### CODE REVIEW

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request created: [1292116](https://a.yandex-team.ru/review/1292116)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1292116](https://a.yandex-team.ru/review/1292116)

**Comment by arcadia-devtools** [comment]
Check [1292116](https://a.yandex-team.ru/review/1292116) passed

**Pull request merged**
