### PR TITLE
 [node-package] CI script for node-package

### PR DESCRIPTION
**Pull request by IKholopov**
#1592

- CI script simplifying deployment preparation procedure
- Some internal reorganization of build scripts

### CODE REVIEW

**Comment by nikitxskv** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@nikitxskv, internal review request created: [1773105](https://a.yandex-team.ru/review/1773105)

**Comment by arcadia-devtools** [comment]
Check [1773105](https://a.yandex-team.ru/review/1773105) passed

**Pull request merged**
