### PR TITLE
Update LICENSE 2021

### PR DESCRIPTION
**Pull request by masguit42**
Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

### CODE REVIEW

**Comment by kizill** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
@masguit42, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

**Comment by arcadia-devtools** [comment]
@kizill, internal review request created: [1981772](https://a.yandex-team.ru/review/1981772)

**Comment by masguit42** [comment]
@arcadia-devtools, I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

**Pull request merged**
